name: Nightly Selenium + Cucumber Tests

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight UTC
  workflow_dispatch:    # allows manual runs

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 24
          cache: maven

      - name: Create timestamp for reports
        id: timestamp
        run: echo "DATE=$(Get-Date -Format 'yyyyMMdd_HHmmss')" >> $GITHUB_ENV
        shell: powershell
      - name: Save report to repo
        run: |
          mkdir reports/%DATE%
          copy target/cucumber-reports.html reports/%DATE%/
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add reports/%DATE%/*
          git commit -m "Add nightly report %DATE%"
          git push
          shell: powershell
        
